name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PKEY: ${{ secrets.PKEY }}

    strategy:
      max-parallel: 1
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn run test
